@startuml
class ChangeWallpaperWebVisual <<partial>> {
    + ChangeWallpaperWebVisual()
    + GetCommand() : ITaskCommand
}
UserControl <|-- ChangeWallpaperWebVisual
ICommandVisual <|-- ChangeWallpaperWebVisual
@enduml
