@startuml
class ChangeWallpaperLocalVisual <<partial>> {
    + ChangeWallpaperLocalVisual()
    + GetCommand() : ITaskCommand
}
UserControl <|-- ChangeWallpaperLocalVisual
ICommandVisual <|-- ChangeWallpaperLocalVisual
@enduml
