@startuml
class SendNotificationEmailVisual <<partial>> {
    + SendNotificationEmailVisual()
    + GetCommand() : ITaskCommand
}
UserControl <|-- SendNotificationEmailVisual
ICommandVisual <|-- SendNotificationEmailVisual
@enduml
