@startuml
class SendNotificationToastVisual <<partial>> {
    + SendNotificationToastVisual()
    + GetCommand() : ITaskCommand
}
UserControl <|-- SendNotificationToastVisual
ICommandVisual <|-- SendNotificationToastVisual
@enduml
