@startuml
class StartWebProcessVisual <<partial>> {
    + StartWebProcessVisual()
    + GetCommand() : ITaskCommand
}
UserControl <|-- StartWebProcessVisual
ICommandVisual <|-- StartWebProcessVisual
@enduml
