@startuml
class StartWindowsProcessVisual <<partial>> {
    + StartWindowsProcessVisual()
    + GetCommand() : ITaskCommand
}
UserControl <|-- StartWindowsProcessVisual
ICommandVisual <|-- StartWindowsProcessVisual
@enduml
