@startuml
class TakeScreenshotVisual <<partial>> {
    + TakeScreenshotVisual()
    + GetCommand() : ITaskCommand
}
UserControl <|-- TakeScreenshotVisual
ICommandVisual <|-- TakeScreenshotVisual
@enduml
