@startuml
class BasicConsole <<static>> {
    + {static} isDirty : bool = false
    + {static} WriteLine(message:string, color:Color) : void
}
struct LineStruct {
    + text : string
    + LineStruct(text:string, color:Color)
}
class "List`1"<T> {
}
BasicConsole --> "logger" AbstractLogger
BasicConsole o-> "lines<LineStruct>" "List`1"
BasicConsole +-- LineStruct
LineStruct --> "color" Color
@enduml
