@startuml
class TaskSchedulerSettings <<static>> {
    + {static} TaskInterval : int <<get>> <<set>> = 1000
    + {static} EmailServer : string <<get>> <<set>> = "smtp-relay.brevo.com"
    + {static} EmailServerPort : int <<get>> <<set>> = 587
    + {static} EmailServerUsername : string <<get>> <<set>> = "814bb3001@smtp-brevo.com"
    + {static} EmailServerPassword : string <<get>> <<set>> = "kY8wAcCEa6qbyg5x"
    + {static} EmailFrom : string <<get>> <<set>> = "mehmetexpress3@gmail.com"
}
@enduml
