@startuml
class TaskScheduler {
    + _hour : int
    + _minute : int
    + TaskScheduler(name:string, hour:int, minute:int)
    + AddTask(handler:TaskHandler) : void
    + <<async>> ExecuteAllAsync() : Task
    + <<override>> ToString() : string
}
@enduml
